DELETE http://localhost:3003/api/persons/641b9ba7b652e90fdb0a5f97

###
POST http://localhost:3003/api/blogs/
content-type: application/json

{
  "title": "MiduDev",
  "author": "Miguel Angel Duran",
  "url": "https://midu.dev/",
  "likes": 1
}

###
GET http://localhost:3003/api/blogs/

###
GET http://localhost:3003/api/blogs/641b9ba7b652e90fdb0a5f97